exercises/intro/intro1.cairo
=> #15 The first exercise

Cargo.lock, Cargo.toml, corelib/array.cairo, corelib/debug.cairo, corelib/dict.cairo, corelib/ec.cairo, corelib/hash.cairo, corelib/integer.cairo, corelib/lib.cairo, corelib/nullable.cairo, corelib/option.cairo, corelib/result.cairo, corelib/serde.cairo, corelib/starknet.cairo, corelib/test.cairo, corelib/traits.cairo, src/Cargo.toml, src/cairo-runner.rs
Updates the Cairo dependencies and core library to v1.0.0-alpha.2
~30mins
Fixes #14
=> feat: v1.0.0-alpha.2 update

exercises/variables/README.md, exercises/variables/variables1.cairo, exercises/variables/variables2.cairo, exercises/variables/variables3.cairo, exercises/variables/variables4.cairo, exercises/variables/variables5.cairo, exercises/variables/variables6.cairo, info.toml
=> feat: variables exercices

exercises/structs/README.md, exercises/structs/structs1.cairo, exercises/structs/structs2.cairo, exercises/structs/structs3.cairo, info.toml, src/exercise.rs
Implements #9 
Time spent: 2hrs
=> feat: struct exercices

exercises/functions/README.md, exercises/functions/functions1.cairo, exercises/functions/functions2.cairo, exercises/functions/functions3.cairo, exercises/functions/functions4.cairo, info.toml
~ 1 hour
Ideally we should update the cairo version because of some missing features ;)
=> feat: functions exercices

.gitignore, Cargo.lock, Cargo.toml, corelib/array.cairo, corelib/dict.cairo, corelib/ec.cairo, corelib/ecdsa.cairo, corelib/hash.cairo, corelib/integer.cairo, corelib/internal.cairo, corelib/lib.cairo, corelib/option.cairo, corelib/result.cairo, corelib/serde.cairo, corelib/starknet.cairo, corelib/starknet_serde.cairo, corelib/test.cairo, corelib/traits.cairo, corelib/zeroable.cairo, exercises/functions/functions3.cairo, exercises/functions/functions4.cairo, exercises/structs/structs2.cairo, exercises/variables/variables5.cairo, exercises/variables/variables6.cairo, src/Cargo.toml, src/cairo-runner.rs, src/cairo-tester.rs
Fixes #24.
Some exercises were adapted to the updates in the core library.
=> feat: update to last cairo version

exercises/if/README.md, exercises/if/if1.cairo, exercises/if/if2.cairo, info.toml
=> feat: if exercices

exercises/primitive_types/README.md, exercises/primitive_types/primitive_types1.cairo, exercises/primitive_types/primitive_types2.cairo, exercises/primitive_types/primitive_types3.cairo, exercises/primitive_types/primitive_types4.cairo, info.toml
Fixes #29 
Time spent: ~ 2 hours
=> feat: primitive types exercises

exercises/arrays/README.md, exercises/arrays/arrays1.cairo, exercises/arrays/arrays2.cairo, exercises/arrays/arrays3.cairo, info.toml
Fixes #12 
These exercises demonstrate how to create arrays and use its methods.
Time spent: ~2 hrs
=> feat: arrays

src/main.rs
A wrapper around watch.
For every exercise, checks its path in `./solutions` can be compiled.
=> Command: compile_solutions

Cargo.lock, Cargo.toml, corelib/array.cairo, corelib/ec.cairo, corelib/lib.cairo, corelib/option.cairo, corelib/result.cairo, corelib/starknet.cairo, corelib/starknet/contract_address.cairo, corelib/starknet/storage_access.cairo, corelib/starknet_testing.cairo, corelib/test.cairo, exercises/arrays/arrays2.cairo, exercises/arrays/arrays3.cairo, src/Cargo.toml
Fixes #39 
Time spent:  ~ 30 mins
=> update: v1.0.0-alpha.3

exercises/quizs/quizs1.cairo
- Corrected calculations for prices 3 & 4
- Added required second arg in `asserts` (failure message)
=> fix: correct price calculations and add error messages

exercises/operations/operations1.cairo
=> modify operations1 as felt doesn't support `/`

exercises/enums/README.md, exercises/enums/enums1.cairo, exercises/enums/enums2.cairo, exercises/enums/enums3.cairo, exercises/operations/operations1.cairo, exercises/options/options2.cairo, info.toml
Closes #45 
Fixes a problem in #36 with operations1. The exercise needed felt division, which is not implemented. There was also ap problem with the test values
Time spent: ~ 3 hours
=> feat: enums

exercises/options/options1.cairo
=> fix: remove options1 solution

exercises/arrays/arrays1.cairo, exercises/arrays/arrays2.cairo, exercises/arrays/arrays3.cairo, exercises/enums/enums2.cairo, exercises/move_semantics/move_semantics1.cairo, exercises/move_semantics/move_semantics2.cairo, exercises/move_semantics/move_semantics3.cairo, exercises/move_semantics/move_semantics4.cairo, exercises/move_semantics/move_semantics5.cairo, exercises/options/options1.cairo, exercises/options/options2.cairo, exercises/options/options3.cairo, info.toml
=> refactor: remove turbofish syntax in types

README.md
1. Run `git clone https://github.com/vikkydataseo/starklings-cairo1.git` to clone the repo
2. Run `cd starklings-cairo1`
3. Run `cargo run --bin starklings`, this might take a while the first time.
=> Adding `git clone` to the read me file and re-numbering the steps accordingly 

info.toml
=> fix: functions4 hint

README.md
@enitrat Does this look good? Anything we want to add/remove?
=> Readme for contributing

exercises/arrays/README.md, exercises/enums/README.md, exercises/if/README.md, exercises/structs/README.md, exercises/traits/README.md, exercises/variables/README.md, info.toml
=> fix: dead links

exercises/structs/README.md
=> Update Struct Exercise README.md

README.md
=> Onlydust shield README.md

info.toml
=> Updated info.toml

exercises/operations/operations2.cairo
=> Typo rectified in operations2.cairo

Cargo.toml, README.md, exercises/operations/operations1.cairo
Updating my email in `cargo.toml` authors
Trimming additional asserts from `operations1.cairo`.
Added telegram shield
=> Minor updates

exercises/starknet/basics/starknet1.cairo, exercises/starknet/basics/starknet2.cairo, exercises/starknet/basics/starknet3.cairo, exercises/starknet/basics/starknet4.cairo, info.toml, src/starklings_tester.rs
Basic contract exercises.
I will make another PR to handle cross-contract calls and else|
Time spent: 2 hours
Closes #102
=> feat: basic contract exercises

src/starklings_runner.rs
Closes #107 
I previously added the SN plugin in the `starklings_tester` binary but not in the regular compiler/runner.
=> feat: starknet plugin runner

exercises/starknet/basics/starknet4.cairo
Hello, just a smol pr to fix #123
=> Fix typo in starknet4 test_stock

exercises/starknet/README.md
=> fix(typo): Update README.md

info.toml
=> chore(#133): hint says array

exercises/enums/enums3.cairo
=> Fix: Remove custom `impl` from enums3 exercise

exercises/enums/README.md, exercises/options/README.md, info.toml
The link is the link doesn't work because the number of the chapter in the book changed
=> fix wrong url cairo book chapter

README.md, src/main.rs
=> chore: -r for faster runs

src/main.rs, src/verify.rs
Fix watch logs,
They get messed up with prints for tests/compiles.
=> fix: command stdout

src/verify.rs
Removed,
```
Output:
================
================
```
=> chore: remove empty output

info.toml
=> chore: fix dict3 deadlink

README.md
fixes #212 for easy code copying
=> chore: readme code blocks

Cargo.lock, Cargo.toml, runner-crate/Scarb.toml, src/scarb.rs
Fixes #225
- update cairo
- enable gas in test target
=> fix: variable data for statement not found

exercises/starknet/basics/starknet3.cairo, info.toml
=> Issue Update Starknet Exercises `LegacyMap` to `Map`  #224

app/client/package-lock.json, app/client/src/components/pages/Workspace/ExerciseList.tsx, app/client/src/components/pages/Workspace/Workspace.tsx, app/client/src/queries/useGetExercise.tsx, app/client/src/queries/useGetExercises.tsx, app/client/src/utils/getName.ts
App was expecting id on exercises, and that broke the exercise list
=> Fix exercise list

app/client/package-lock.json, app/client/src/components/pages/Workspace/ExerciseList.tsx, app/client/src/pkg/module/LICENSE_APACHE, app/client/src/pkg/module/README.md, app/client/src/pkg/module/package.json, app/client/src/pkg/module/wasm-cairo.d.ts, app/client/src/pkg/module/wasm-cairo.js, app/client/src/pkg/module/wasm-cairo_bg.wasm.d.ts, app/client/src/queries/useGetExercise.tsx, app/client/src/queries/useGetExercises.tsx, app/client/src/utils/getName.ts, app/client/src/workers/cairoWorker.ts
We are going to use a fork of [Cairo WASM v0.10.2](https://github.com/cryptonerdcn/wasm-cairo/releases/tag/v0.10.2) because the original version has issues with logging.  
When running tests and encountering errors, we get the following log output:  
```
test result: FAILED. 0 passed; 2 failed; 0 ignored
```
This log provides very little information, making it difficult to identify where the failure occurs.  
In contrast, our version of Cairo WASM provides the following log:  
```
TEST RESULT:  Wasm-Cairo Test outputs: 
test astro::test_poly ... fail (gas usage est.: 8270)
test astro::test_poly_duplicate ... fail (gas usage est.: 8270)
failures:
astro::test_poly - Panicked with 0x4572726f72206d657373616765 ('Error message').
astro::test_poly_duplicate - Panicked with …
```
=> Bump cairo 2.8.2

app/client/src/queries/useGetExercises.tsx
=> fix bug on completed exercises

app/client/src/components/layout/About.tsx
=> chore:  update about component - change GitHub links and Cairo version

exercises/enums/enums1.cairo, exercises/enums/enums2.cairo, exercises/enums/enums3.cairo
=> chore: fix enum exercises

app/client/cypress/e2e/intro.cy.ts, app/client/cypress/fixtures/starknet6.cairo, exercises/starknet/components/starknet6.cairo
=> fix: update contract `starknet6.cairo`

app/client/src/App.tsx, app/client/src/components/layout/BasicLayout.tsx, app/client/src/components/pages/Check/CheckGitHubAccount.tsx, app/client/src/queries/useGetExercises.tsx
https://github.com/user-attachments/assets/a9052652-43f7-4f4d-ba35-b52006269731
=> chore: add menu Mentor
