shramee/starklings

- Cargo.toml
- README.md
- info.toml
- src/Cargo.toml
- src/exercise.rs
- src/main.rs
- src/run.rs
- src/starklings_runner.rs
- src/starklings_tester.rs
- src/verify.rs
- tests/integration_tests.rs
Fixes #25 
The user will need to build the binaries before using starklings with `cargo build --all`.
We invoke directly the executables in starklings instead of using cargo, which speeds things up _at least_ 10x.
Time spent: 3 hours
> fix: speed up cairo-runner and cairo-tester in starklings

- exercises/arrays/README.md
- Medium link was malformed
- Updated Core library link as it has moved to `.../src/...`
> Fix links in array README

- info.toml
Changes the order of the exercises for a more natural and sequential approach to the language. This ensures that every concept used in the exercises has been seen before.
> refactor: exercises order

- exercises/quizs/quizs1.cairo
Prices have been changed in #53 but imho it was a mistake 😅
#53 updated prices means that the first 40 apples cost 3 cairobucks and the next ones 2. But the comments state `If Mary buys more than 40 apples, each apple only costs 2 cairobuck!` which means the first 40 apples should also cost 2 cairobucks.
> Fixed quizs1 prices 3 and 4

- README.md
- src/main.rs
- src/verify.rs
To start watch at a specific exercise pass the name of the exercise to watch command.
For example, to start at `starknet1`,
```
cargo run --bin starklings watch starknet1
```
> Watch start at

- Scarb.toml
due to bug in vscode-cairo extension if scarb is installed it uses scarb's language server which expects this file to be present else it crashes.
see #127
> fix: add expected file

- exercises/move_semantics/move_semantics2.cairo
This PR renamed `fill_array` into `fill_arr` in `move_semantics_2` to match hint content and `move_semantics_[1,3,4]`
> fix: move_semantics_2

- exercises/move_semantics/README.md
- info.toml
Hi, It seems like the links to the Cairo Book (understanding-ownership & references-and-snapshots) are broken (the chapter is incorrect).
> Replace chapter 3 for chapter 4 in the broken links

- info.toml
Starknet3 exercice got no hint, like the 2 previous starknet basics exercices. However for the previous one, the message "No hints this time ;)" was displayed, while nothing is displayed for starknet3 exercice.
> Added Missing Hint Message to Starknet3 Exercise

- exercises/enums/enums1.cairo
- exercises/enums/enums2.cairo
- exercises/enums/enums3.cairo
- exercises/options/options2.cairo
- exercises/options/options3.cairo
A small set of edits to syntax of enums and options exercises with empty 'unit type' `()`
My personal solutions compiled with these small edits
I intend to also submit a PR to the Cairo Book to make the same readability changes for unit types in [6.1 'The option enum'](https://book.cairo-lang.org/ch06-01-enums.html#the-option-enum-and-its-advantages) and [6.2 'The Match Control Flow Construct'](https://book.cairo-lang.org/ch06-02-the-match-control-flow-construct.html)
Thank you for providing and maintaining this excellent resource
> Simplified syntax of unit type enums and options

- exercises/dict/README.md
- exercises/dict/dict1.cairo
- exercises/dict/dict2.cairo
- exercises/dict/dict3.cairo
- info.toml
Resolves: #66
I created 3 exercises about the Felt252Dict data type
> Exercises on dicts

- exercises/dict/dict1.cairo
- exercises/dict/dict2.cairo
Found a couple of typos on the `dict` exercises, so I fixed them :)
> fix typos on dict exercises

- exercises/dict/README.md
- exercises/enums/README.md
- exercises/functions/README.md
- exercises/if/README.md
- exercises/loops/README.md
- exercises/modules/readme.md
- exercises/move_semantics/README.md
- exercises/operations/README.md
- exercises/options/README.md
- exercises/primitive_types/README.md
- exercises/starknet/README.md
- exercises/structs/README.md
- exercises/traits/README.md
- exercises/variables/README.md
- info.toml
Fix broken links in REAME files and hints
The Cairo book domain was changed to https://book.cairo-lang.org, so all links are broken :(
Fixed them in this pull request 💪
> Fix broken links in REAME files and hints

- src/scarb.rs
> fix: casm runner args and gas

- src/main.rs
- src/run.rs
- src/scarb.rs
- src/ui.rs
- src/utils.rs
- src/verify.rs
> Improved logs and code keeping

- exercises/move_semantics/move_semantics1.cairo
> remove unnecessary `clone()` usage in move_semantics1.cairo file

- exercises/options/README.md
Improved grammar and readability in documentation for `Option` type usage and applications"
> Updated README.md for Options

- .github/workflows/rust.yml
- Cargo.toml
- src/scarb.rs
This is a naive attempt to fix https://github.com/shramee/starklings-cairo1/issues/216 - as without these Starklings refuse to compile.
> Updating Scarb references to latest v2.8.1

- runner-crate/Scarb.toml
- src/scarb.rs
- tests/fixture/cairo/runner-crate/Scarb.toml
- tests/fixture/cairo/testPass.cairo
> chore: upgrade scarb and cairo v2.8

- app/client/src/queries/useGetExercise.tsx
Changed to allow empty exercise where user might be required to start from scratch.
> fix(app): throws error on empty code
